{
    "assignee": null,
    "assignees": [],
    "body": "Hi,\n\nI am currently experiencing a python3 cythonize bug. The same code works under python 2.7.\nI think I was able to pinpoint the cause which I explain below.\n\n```\n>>> print(cython.__version__)\n0.25.1\n```\n\nHere is what I am trying to compile with python3.4:\n\n```\nextensions = [\n    Extension(\"first_ext\", [\"first_ext.pyx\", \"somefile.c\"],\n        include_dirs = [...],\n        libraries = [...],\n        library_dirs = [...]),\n    Extension(\"second_ext\", [\"second_ext.pyx\", \"somefile2.c\"],\n        include_dirs = [...],\n        libraries = [...],\n        library_dirs = [...]),\n]\nsetup(\n    name = \"My hello app\",\n    ext_modules = cythonize(extensions),\n)\n```\n\nHere is the error I am getting:\n\n```\nTraceback (most recent call last):\n  File \"setup.py\", line 137, in <module>\n    , extra_link_args=['-fopenmp'])\n  File \"./.virtualenvs/envpy34/lib/python3.4/site-packages/Cython/Build/Dependencies.py\", line 886, in cythonize\n    to_compile.sort()\nTypeError: unorderable types: dict() < dict()\n```\n\nThe `to_compile` list contains tuples with some data like this:\n\n[(0, 'path/first_ext.pyx', 'path/first_ext.c', None, False, <Cython.Compiler.Main.CompilationOptions object at 0x7fd18d3eae10>, True, **{'meta_data_dict_first_ext'}**),\n(0, 'path/second_ext.pyx', 'path/second_ext.c', None, False, <Cython.Compiler.Main.CompilationOptions object at 0x7fd18d3eae10>, True, **{'meta_data_dict_second_ext}**)]\n\nNotice the bold metadata dicts (the last entry of each tuple in `to_compile`).\n\nThe reason why it fails is that python2.7 is able to sort tuples which have dicts, python3 is not able to do it out of the box.\n\nHere a relevant link to a [stackoverflow discussion](http://stackoverflow.com/questions/22333388/dicts-are-not-orderable-in-python-3)\n\nAs a workaround instead of cythonizing a list of Extensions it is possible to cythonize one Extension at a time. This has some disadvantages though like multiple times compiling the same files.\n",
    "closed_at": "2016-11-16T05:10:35Z",
    "comment_data": [
        {
            "body": "It should never get to the dicts unless everything preceding it in the tuple is the same. Do you perhaps have duplicate entries in your Extension list? (If this is indeed it, we should provide a better error.)",
            "created_at": "2016-10-27T19:24:19Z",
            "html_url": "https://github.com/cython/cython/issues/1505#issuecomment-256743848",
            "id": 256743848,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1505",
            "updated_at": "2016-10-27T19:24:19Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/256743848",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/486017?v=3",
                "events_url": "https://api.github.com/users/robertwb/events{/privacy}",
                "followers_url": "https://api.github.com/users/robertwb/followers",
                "following_url": "https://api.github.com/users/robertwb/following{/other_user}",
                "gists_url": "https://api.github.com/users/robertwb/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/robertwb",
                "id": 486017,
                "login": "robertwb",
                "organizations_url": "https://api.github.com/users/robertwb/orgs",
                "received_events_url": "https://api.github.com/users/robertwb/received_events",
                "repos_url": "https://api.github.com/users/robertwb/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/robertwb/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/robertwb/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/robertwb"
            }
        },
        {
            "body": "I can confirm that it has something to do with having multiple times the same pyx file in extensions I saw this error when I had this case:\r\n\r\n```\r\nextensions = [\r\n    Extension(\"first_ext\", [\"first_ext.pyx\", \"signals.pyx\", \"somecfile1.c\"],\r\n        include_dirs = [...],\r\n        libraries = [...],\r\n        library_dirs = [...]),\r\n    Extension(\"second_ext\", [\"second_ext.pyx\", \"signals.pyx\", \"somecfile2.c\"],\r\n        include_dirs = [...],\r\n        libraries = [...],\r\n        library_dirs = [...]),\r\n]\r\nsetup(\r\n    name = \"My hello app\",\r\n    ext_modules = cythonize(extensions),\r\n)\r\n```\r\n\r\nSignals.pyx looks like this:\r\n\r\n```\r\nfrom libc.stdint cimport uint32_t\r\nfrom cpython.exc cimport PyErr_CheckSignals\r\n\r\ncdef public void check_signals(uint32_t* stop) with gil:\r\n  PyErr_CheckSignals()\r\n```\r\n\r\n**somefile1.c** and **somefile2.c** expect that the function **check_signals** is defined somewhere and since it uses the python context it needs to be defined in a pyx file. How can check_signals be used by both .c files if it is not defined in a pyx file? Is this not the way it should be done?",
            "created_at": "2016-10-28T08:12:27Z",
            "html_url": "https://github.com/cython/cython/issues/1505#issuecomment-256862201",
            "id": 256862201,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1505",
            "updated_at": "2016-10-28T08:14:05Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/256862201",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/17453385?v=3",
                "events_url": "https://api.github.com/users/the-neworder/events{/privacy}",
                "followers_url": "https://api.github.com/users/the-neworder/followers",
                "following_url": "https://api.github.com/users/the-neworder/following{/other_user}",
                "gists_url": "https://api.github.com/users/the-neworder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/the-neworder",
                "id": 17453385,
                "login": "the-neworder",
                "organizations_url": "https://api.github.com/users/the-neworder/orgs",
                "received_events_url": "https://api.github.com/users/the-neworder/received_events",
                "repos_url": "https://api.github.com/users/the-neworder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/the-neworder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/the-neworder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/the-neworder"
            }
        },
        {
            "body": "See http://cython.readthedocs.io/en/latest/src/userguide/sharing_declarations.html",
            "created_at": "2016-11-16T05:10:31Z",
            "html_url": "https://github.com/cython/cython/issues/1505#issuecomment-260855747",
            "id": 260855747,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1505",
            "updated_at": "2016-11-16T05:10:31Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/260855747",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/486017?v=3",
                "events_url": "https://api.github.com/users/robertwb/events{/privacy}",
                "followers_url": "https://api.github.com/users/robertwb/followers",
                "following_url": "https://api.github.com/users/robertwb/following{/other_user}",
                "gists_url": "https://api.github.com/users/robertwb/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/robertwb",
                "id": 486017,
                "login": "robertwb",
                "organizations_url": "https://api.github.com/users/robertwb/orgs",
                "received_events_url": "https://api.github.com/users/robertwb/received_events",
                "repos_url": "https://api.github.com/users/robertwb/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/robertwb/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/robertwb/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/robertwb"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1505/comments",
    "created_at": "2016-10-27T16:38:17Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/486017?v=3",
                "events_url": "https://api.github.com/users/robertwb/events{/privacy}",
                "followers_url": "https://api.github.com/users/robertwb/followers",
                "following_url": "https://api.github.com/users/robertwb/following{/other_user}",
                "gists_url": "https://api.github.com/users/robertwb/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/robertwb",
                "id": 486017,
                "login": "robertwb",
                "organizations_url": "https://api.github.com/users/robertwb/orgs",
                "received_events_url": "https://api.github.com/users/robertwb/received_events",
                "repos_url": "https://api.github.com/users/robertwb/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/robertwb/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/robertwb/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/robertwb"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2016-11-16T05:10:35Z",
            "event": "closed",
            "id": 860521653,
            "url": "https://api.github.com/repos/cython/cython/issues/events/860521653"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1505/events",
    "html_url": "https://github.com/cython/cython/issues/1505",
    "id": 185720896,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1505/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1505,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "title": "cythonize python3 bug with extension list",
    "updated_at": "2016-11-16T05:10:35Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1505",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/22150603?v=3",
        "events_url": "https://api.github.com/users/thomas-bottesch/events{/privacy}",
        "followers_url": "https://api.github.com/users/thomas-bottesch/followers",
        "following_url": "https://api.github.com/users/thomas-bottesch/following{/other_user}",
        "gists_url": "https://api.github.com/users/thomas-bottesch/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/thomas-bottesch",
        "id": 22150603,
        "login": "thomas-bottesch",
        "organizations_url": "https://api.github.com/users/thomas-bottesch/orgs",
        "received_events_url": "https://api.github.com/users/thomas-bottesch/received_events",
        "repos_url": "https://api.github.com/users/thomas-bottesch/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/thomas-bottesch/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/thomas-bottesch/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/thomas-bottesch"
    }
}