{
    "assignee": null,
    "assignees": [],
    "body": "I cannot successfully obtain a report of coverage for the Cython module [`dd.cudd`](https://github.com/johnyf/dd/blob/master/dd/cudd.pyx). I have:\r\n\r\n- followed the [Cython instructions for enabling coverage analysis](http://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html#enabling-coverage-analysis)\r\n- ensured that `coverage.py` with its [C extension](https://coverage.readthedocs.io/en/coverage-4.2/plugins.html) are installed, in order for the `Cython.Coverage` plugin to work.\r\n\r\nI am using `nosetests`---I do not know whether `nose` can cause additional difficulties.\r\n\r\nDirectory layout under `/path` roughly:\r\n```\r\ndd/\r\ntests/\r\n```\r\n\r\nNormally, I run `nosetests` within `tests/`, because I want to ensure that `nosetests` will import `dd` from `site-packages` (I have also tried the `-w` option of `nosetests`).\r\nI have tried running `nosetests` both inside the `tests/` directory, and above it.\r\n`nose` does not report any results for `cudd.pyx`.\r\n\r\nWhen `nose --with-coverage --cover-package=dd` runs under `tests/`, it creates a `.coverage` that mentions both a `/path/tests/dd/cudd.pyx` file (nonexistent), as well as the existing `/path/dd/dd/cudd.pyx`. For the existing file, `coverage report` complains that\r\n\r\n```\r\n/path/dd/dd/cudd.pyx   NotPython:\r\nCouldn't parse '/path/dd/dd/cudd.pyx' as Python source: 'invalid syntax' at line 20\r\n```\r\n\r\nAlso, manually editing the wrong path reported in `.coveragerc` produces again the above error.\r\n\r\nThese observations are with:\r\n- `cython == 0.25.1`\r\n- `nose == 1.3.7`\r\n- `coverage == 4.2`\r\n\r\nHow can I get coverage to be reported for Cython modules? It seems that this may be a problem both with paths that `coverage.py` reports, and with failure of `coverage.py` to parse Cython syntax. I am unsure whether this should be addressed by `cython` (e.g., in the `coverage.py` plugin `Cython.Coverage`), or by `coverage.py`, or both.\r\n\r\nMay have some relevance to #1461.",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1508/comments",
    "created_at": "2016-10-29T03:52:11Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1508/events",
    "html_url": "https://github.com/cython/cython/issues/1508",
    "id": 186057475,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1508/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1508,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "cannot report test coverage",
    "updated_at": "2016-10-29T03:52:11Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1508",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3135273?v=3",
        "events_url": "https://api.github.com/users/johnyf/events{/privacy}",
        "followers_url": "https://api.github.com/users/johnyf/followers",
        "following_url": "https://api.github.com/users/johnyf/following{/other_user}",
        "gists_url": "https://api.github.com/users/johnyf/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/johnyf",
        "id": 3135273,
        "login": "johnyf",
        "organizations_url": "https://api.github.com/users/johnyf/orgs",
        "received_events_url": "https://api.github.com/users/johnyf/received_events",
        "repos_url": "https://api.github.com/users/johnyf/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/johnyf/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/johnyf/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/johnyf"
    }
}