{
    "assignee": null,
    "assignees": [],
    "body": "Since I think it might be good to have an open issue for others to find. This is a resurrection of gh-1720.\r\n\r\nDue to http://bugs.python.org/issue25791 on python 3.6 cython will cause warnings such as:\r\n```\r\nTraceback (most recent call last):\r\n  File \"<string>\", line 1, in <module>\r\n  File \"/home/antoine/multidict/multidict/__init__.py\", line 24, in <module>\r\n    __import__('_multidict', globals=globals(), level=1)\r\n  File \"multidict/_multidict.pyx\", line 1, in init multidict._multidict (multidict/_multidict.c:14817)\r\n    import sys\r\nImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\r\n```\r\nupon import. Getting rid of the warning appears to be not very easy, and probably requires gh-1715 to be implemented.\r\n\r\n**Workaround**: If I understand correctly, if the cython module is compiled using `cython -3` mode or uses `from __future__ import absolute_import`, most of these warnings should go away. Also python modules which are imported using the format of e.g. `from . import _ufunc` need to be converted to `from scipy.special import _ufunc`.",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1753/comments",
    "created_at": "2017-06-27T08:03:08Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1753/events",
    "html_url": "https://github.com/cython/cython/issues/1753",
    "id": 238767758,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1753/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1753,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "Spurious ImportWarnings on 3.6+",
    "updated_at": "2017-06-27T08:03:08Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1753",
    "user": {
        "avatar_url": "https://avatars2.githubusercontent.com/u/61977?v=3",
        "events_url": "https://api.github.com/users/seberg/events{/privacy}",
        "followers_url": "https://api.github.com/users/seberg/followers",
        "following_url": "https://api.github.com/users/seberg/following{/other_user}",
        "gists_url": "https://api.github.com/users/seberg/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/seberg",
        "id": 61977,
        "login": "seberg",
        "organizations_url": "https://api.github.com/users/seberg/orgs",
        "received_events_url": "https://api.github.com/users/seberg/received_events",
        "repos_url": "https://api.github.com/users/seberg/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/seberg/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/seberg/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/seberg"
    }
}