{
    "assignee": null,
    "assignees": [],
    "body": "For a package applicaction with pyqt/PySide, Python 3.4 on Windows, appers a window fatal error when shoutdown process manager of multiprocessing",
    "closed_at": "2017-06-29T07:59:31Z",
    "comment_data": [
        {
            "body": "Not Cython issue, CPython issue instead",
            "created_at": "2017-06-29T08:28:31Z",
            "html_url": "https://github.com/cython/cython/issues/1754#issuecomment-311898546",
            "id": 311898546,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1754",
            "updated_at": "2017-06-29T08:28:31Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/311898546",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/6556518?v=3",
                "events_url": "https://api.github.com/users/alfonnews/events{/privacy}",
                "followers_url": "https://api.github.com/users/alfonnews/followers",
                "following_url": "https://api.github.com/users/alfonnews/following{/other_user}",
                "gists_url": "https://api.github.com/users/alfonnews/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/alfonnews",
                "id": 6556518,
                "login": "alfonnews",
                "organizations_url": "https://api.github.com/users/alfonnews/orgs",
                "received_events_url": "https://api.github.com/users/alfonnews/received_events",
                "repos_url": "https://api.github.com/users/alfonnews/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/alfonnews/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/alfonnews/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/alfonnews"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1754/comments",
    "created_at": "2017-06-27T13:22:01Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/6556518?v=3",
                "events_url": "https://api.github.com/users/alfonnews/events{/privacy}",
                "followers_url": "https://api.github.com/users/alfonnews/followers",
                "following_url": "https://api.github.com/users/alfonnews/following{/other_user}",
                "gists_url": "https://api.github.com/users/alfonnews/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/alfonnews",
                "id": 6556518,
                "login": "alfonnews",
                "organizations_url": "https://api.github.com/users/alfonnews/orgs",
                "received_events_url": "https://api.github.com/users/alfonnews/received_events",
                "repos_url": "https://api.github.com/users/alfonnews/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/alfonnews/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/alfonnews/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/alfonnews"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2017-06-29T07:59:31Z",
            "event": "closed",
            "id": 1143719878,
            "url": "https://api.github.com/repos/cython/cython/issues/events/1143719878"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1754/events",
    "html_url": "https://github.com/cython/cython/issues/1754",
    "id": 238849023,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1754/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1754,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "title": "shoutdown process error with python 3.4 and pyqt/PySide",
    "updated_at": "2017-06-29T08:28:31Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1754",
    "user": {
        "avatar_url": "https://avatars0.githubusercontent.com/u/6556518?v=3",
        "events_url": "https://api.github.com/users/alfonnews/events{/privacy}",
        "followers_url": "https://api.github.com/users/alfonnews/followers",
        "following_url": "https://api.github.com/users/alfonnews/following{/other_user}",
        "gists_url": "https://api.github.com/users/alfonnews/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/alfonnews",
        "id": 6556518,
        "login": "alfonnews",
        "organizations_url": "https://api.github.com/users/alfonnews/orgs",
        "received_events_url": "https://api.github.com/users/alfonnews/received_events",
        "repos_url": "https://api.github.com/users/alfonnews/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/alfonnews/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/alfonnews/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/alfonnews"
    }
}