{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "I think Cython is no longer compatible with Python 3.7 because the generated code reaches inside the PyThreadState structure and tries to access non-public structure members that no longer exist.  I found this problem when trying to build lxml's git master HEAD using Python 3.7's git master HEAD in a virtual environment.  Here's an example of the error:\r\n\r\n```\r\n    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DCYTHON_CLINE_IN_TRACEBACK=1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/tmp/py37/include -I/usr/local/include/python3.7m -c src/lxml/etree.c -o build/temp.macosx-10.12-x86_64-3.7/src/lxml/etree.o -w -flat_namespace\r\n    src/lxml/etree.c:257734:21: error: no member named 'exc_type' in 'struct _ts'\r\n        *type = tstate->exc_type;\r\n                ~~~~~~  ^\r\n    src/lxml/etree.c:257735:22: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?\r\n        *value = tstate->exc_value;\r\n                         ^~~~~~~~~\r\n                         curexc_value\r\n    /usr/local/include/python3.7m/pystate.h:169:15: note: 'curexc_value' declared here\r\n        PyObject *curexc_value;\r\n                  ^\r\n    src/lxml/etree.c:257736:19: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?\r\n        *tb = tstate->exc_traceback;\r\n                      ^~~~~~~~~~~~~\r\n                      curexc_traceback\r\n    /usr/local/include/python3.7m/pystate.h:170:15: note: 'curexc_traceback' declared here\r\n        PyObject *curexc_traceback;\r\n                  ^\r\n```\r\n\r\nLooking an example of the generated code:\r\n\r\n```c\r\n/* SaveResetException */\r\n  #if CYTHON_FAST_THREAD_STATE\r\nstatic CYTHON_INLINE void __Pyx__ExceptionSave(PyThreadState *tstate, PyObject **type, PyObject **value, PyObject **tb) {\r\n    *type = tstate->exc_type;\r\n    *value = tstate->exc_value;\r\n    *tb = tstate->exc_traceback;\r\n    Py_XINCREF(*type);\r\n    Py_XINCREF(*value);\r\n    Py_XINCREF(*tb);\r\n```\r\n\r\nand indeed `exc_type`, `exc_value` and `exc_traceback` do not exist in Python 3.7.\r\n\r\nThe generated code should probably be using `PyErr_Fetch()` instead.  https://docs.python.org/3.7/c-api/exceptions.html#c.PyErr_Fetch",
    "closed_at": "2017-11-03T09:34:43Z",
    "comment_data": [
        {
            "author_association": "OWNER",
            "body": "Have you tried our current head?\n\nOn Nov 2, 2017 7:20 PM, \"Barry Warsaw\" <notifications@github.com> wrote:\n\n> I think Cython is no longer compatible with Python 3.7 because the\n> generated code reaches inside the PyThreadState structure and tries to\n> access non-public structure members that no longer exist. I found this\n> problem when trying to build lxml's git master HEAD using Python 3.7's git\n> master HEAD in a virtual environment. Here's an example of the error:\n>\n>     gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DCYTHON_CLINE_IN_TRACEBACK=1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/tmp/py37/include -I/usr/local/include/python3.7m -c src/lxml/etree.c -o build/temp.macosx-10.12-x86_64-3.7/src/lxml/etree.o -w -flat_namespace\n>     src/lxml/etree.c:257734:21: error: no member named 'exc_type' in 'struct _ts'\n>         *type = tstate->exc_type;\n>                 ~~~~~~  ^\n>     src/lxml/etree.c:257735:22: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?\n>         *value = tstate->exc_value;\n>                          ^~~~~~~~~\n>                          curexc_value\n>     /usr/local/include/python3.7m/pystate.h:169:15: note: 'curexc_value' declared here\n>         PyObject *curexc_value;\n>                   ^\n>     src/lxml/etree.c:257736:19: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?\n>         *tb = tstate->exc_traceback;\n>                       ^~~~~~~~~~~~~\n>                       curexc_traceback\n>     /usr/local/include/python3.7m/pystate.h:170:15: note: 'curexc_traceback' declared here\n>         PyObject *curexc_traceback;\n>                   ^\n>\n> Looking an example of the generated code:\n>\n> /* SaveResetException */\n>   #if CYTHON_FAST_THREAD_STATEstatic CYTHON_INLINE void __Pyx__ExceptionSave(PyThreadState *tstate, PyObject **type, PyObject **value, PyObject **tb) {\n>     *type = tstate->exc_type;\n>     *value = tstate->exc_value;\n>     *tb = tstate->exc_traceback;\n>     Py_XINCREF(*type);\n>     Py_XINCREF(*value);\n>     Py_XINCREF(*tb);\n>\n> and indeed exc_type, exc_value and exc_traceback do not exist in Python\n> 3.7.\n>\n> The generated code should probably be using PyErr_Fetch() instead.\n> https://docs.python.org/3.7/c-api/exceptions.html#c.PyErr_Fetch\n>\n> â€”\n> You are receiving this because you are subscribed to this thread.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/cython/cython/issues/1978>, or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAdqgaD4YAX4naLK4puqikjgI6Q8wldWks5synhbgaJpZM4QQlWT>\n> .\n>\n",
            "created_at": "2017-11-03T03:18:00Z",
            "html_url": "https://github.com/cython/cython/issues/1978#issuecomment-341614517",
            "id": 341614517,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1978",
            "updated_at": "2017-11-03T03:18:00Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/341614517",
            "user": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/486017?v=4",
                "events_url": "https://api.github.com/users/robertwb/events{/privacy}",
                "followers_url": "https://api.github.com/users/robertwb/followers",
                "following_url": "https://api.github.com/users/robertwb/following{/other_user}",
                "gists_url": "https://api.github.com/users/robertwb/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/robertwb",
                "id": 486017,
                "login": "robertwb",
                "organizations_url": "https://api.github.com/users/robertwb/orgs",
                "received_events_url": "https://api.github.com/users/robertwb/received_events",
                "repos_url": "https://api.github.com/users/robertwb/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/robertwb/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/robertwb/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/robertwb"
            }
        },
        {
            "author_association": "OWNER",
            "body": "Duplicate of #1955.",
            "created_at": "2017-11-03T09:34:43Z",
            "html_url": "https://github.com/cython/cython/issues/1978#issuecomment-341656115",
            "id": 341656115,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1978",
            "updated_at": "2017-11-03T09:34:43Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/341656115",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "AFAICT, current Cython head does *not* fix the problem.  I provided additional details on #1955 and will follow up there.",
            "created_at": "2017-11-03T18:20:00Z",
            "html_url": "https://github.com/cython/cython/issues/1978#issuecomment-341786886",
            "id": 341786886,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1978",
            "updated_at": "2017-11-03T18:20:00Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/341786886",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/210184?v=4",
                "events_url": "https://api.github.com/users/warsaw/events{/privacy}",
                "followers_url": "https://api.github.com/users/warsaw/followers",
                "following_url": "https://api.github.com/users/warsaw/following{/other_user}",
                "gists_url": "https://api.github.com/users/warsaw/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/warsaw",
                "id": 210184,
                "login": "warsaw",
                "organizations_url": "https://api.github.com/users/warsaw/orgs",
                "received_events_url": "https://api.github.com/users/warsaw/received_events",
                "repos_url": "https://api.github.com/users/warsaw/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/warsaw/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/warsaw/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/warsaw"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1978/comments",
    "created_at": "2017-11-03T02:20:10Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2017-11-03T09:34:43Z",
            "event": "closed",
            "id": 1324526584,
            "url": "https://api.github.com/repos/cython/cython/issues/events/1324526584"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2017-11-03T09:35:04Z",
            "event": "labeled",
            "id": 1324527011,
            "label": {
                "color": "444444",
                "name": "R: duplicate"
            },
            "url": "https://api.github.com/repos/cython/cython/issues/events/1324527011"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1978/events",
    "html_url": "https://github.com/cython/cython/issues/1978",
    "id": 270862465,
    "labels": [
        {
            "color": "444444",
            "default": false,
            "id": 425556894,
            "name": "R: duplicate",
            "url": "https://api.github.com/repos/cython/cython/labels/R:%20duplicate"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1978/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1978,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "title": "Cython incompatible with Python 3.7",
    "updated_at": "2017-11-03T18:20:01Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1978",
    "user": {
        "avatar_url": "https://avatars0.githubusercontent.com/u/210184?v=4",
        "events_url": "https://api.github.com/users/warsaw/events{/privacy}",
        "followers_url": "https://api.github.com/users/warsaw/followers",
        "following_url": "https://api.github.com/users/warsaw/following{/other_user}",
        "gists_url": "https://api.github.com/users/warsaw/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/warsaw",
        "id": 210184,
        "login": "warsaw",
        "organizations_url": "https://api.github.com/users/warsaw/orgs",
        "received_events_url": "https://api.github.com/users/warsaw/received_events",
        "repos_url": "https://api.github.com/users/warsaw/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/warsaw/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/warsaw/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/warsaw"
    }
}