{
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "```python\r\n======================================================================\r\nFAIL: numpy_subarray ()\r\nDoctest: numpy_subarray\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/lib64/python2.7/doctest.py\", line 2226, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for numpy_subarray\r\n  File \"/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/c/numpy_subarray/numpy_subarray.so\", line 447, in numpy_subarray\r\n----------------------------------------------------------------------\r\nFile \"/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/c/numpy_subarray/numpy_subarray.so\", line 450, in numpy_subarray\r\nFailed example:\r\n    test_record_subarray()\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/usr/lib64/python2.7/doctest.py\", line 1315, in __run\r\n        compileflags, 1) in test.globs\r\n      File \"<doctest numpy_subarray[0]>\", line 1, in <module>\r\n        test_record_subarray()\r\n      File \"tests/run/numpy_subarray.pyx\", line 23, in numpy_subarray.test_record_subarray\r\n        assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),\r\n    AssertionError\r\n======================================================================\r\nFAIL: numpy_subarray ()\r\nDoctest: numpy_subarray\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/lib64/python2.7/doctest.py\", line 2226, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for numpy_subarray\r\n  File \"/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/cpp/numpy_subarray/numpy_subarray.so\", line 146, in numpy_subarray\r\n----------------------------------------------------------------------\r\nFile \"/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/cpp/numpy_subarray/numpy_subarray.so\", line 149, in numpy_subarray\r\nFailed example:\r\n    test_record_subarray()\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/usr/lib64/python2.7/doctest.py\", line 1315, in __run\r\n        compileflags, 1) in test.globs\r\n      File \"<doctest numpy_subarray[0]>\", line 1, in <module>\r\n        test_record_subarray()\r\n      File \"tests/run/numpy_subarray.pyx\", line 23, in numpy_subarray.test_record_subarray\r\n        assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),\r\n    AssertionError\r\n----------------------------------------------------------------------\r\n```\r\n\r\nHappens only on ppc64 and s390x which are BE.",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "OWNER",
            "body": "Thanks for the report. Could you retry it with the latest master? I added output to the assertions so that we can actually see what it wrong here. Interesting enough, that test has been around since 2013. Since I don't have such a system available, any debugging information that you could provide would be appreciated.",
            "created_at": "2017-11-06T20:30:12Z",
            "html_url": "https://github.com/cython/cython/issues/1982#issuecomment-342276620",
            "id": 342276620,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1982",
            "updated_at": "2017-11-06T20:30:12Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/342276620",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1982/comments",
    "created_at": "2017-11-06T06:09:18Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1982/events",
    "html_url": "https://github.com/cython/cython/issues/1982",
    "id": 271368650,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1982/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1982,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "2 tests fail on Big Endian on 0.27.3",
    "updated_at": "2017-11-06T20:30:12Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1982",
    "user": {
        "avatar_url": "https://avatars1.githubusercontent.com/u/2866862?v=4",
        "events_url": "https://api.github.com/users/ignatenkobrain/events{/privacy}",
        "followers_url": "https://api.github.com/users/ignatenkobrain/followers",
        "following_url": "https://api.github.com/users/ignatenkobrain/following{/other_user}",
        "gists_url": "https://api.github.com/users/ignatenkobrain/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/ignatenkobrain",
        "id": 2866862,
        "login": "ignatenkobrain",
        "organizations_url": "https://api.github.com/users/ignatenkobrain/orgs",
        "received_events_url": "https://api.github.com/users/ignatenkobrain/received_events",
        "repos_url": "https://api.github.com/users/ignatenkobrain/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/ignatenkobrain/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ignatenkobrain/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/ignatenkobrain"
    }
}