{
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "```python\r\n======================================================================\r\nFAIL: numpy_subarray ()\r\nDoctest: numpy_subarray\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/lib64/python2.7/doctest.py\", line 2226, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for numpy_subarray\r\n  File \"/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/c/numpy_subarray/numpy_subarray.so\", line 447, in numpy_subarray\r\n----------------------------------------------------------------------\r\nFile \"/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/c/numpy_subarray/numpy_subarray.so\", line 450, in numpy_subarray\r\nFailed example:\r\n    test_record_subarray()\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/usr/lib64/python2.7/doctest.py\", line 1315, in __run\r\n        compileflags, 1) in test.globs\r\n      File \"<doctest numpy_subarray[0]>\", line 1, in <module>\r\n        test_record_subarray()\r\n      File \"tests/run/numpy_subarray.pyx\", line 23, in numpy_subarray.test_record_subarray\r\n        assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),\r\n    AssertionError\r\n======================================================================\r\nFAIL: numpy_subarray ()\r\nDoctest: numpy_subarray\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/lib64/python2.7/doctest.py\", line 2226, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for numpy_subarray\r\n  File \"/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/cpp/numpy_subarray/numpy_subarray.so\", line 146, in numpy_subarray\r\n----------------------------------------------------------------------\r\nFile \"/builddir/build/BUILD/cython-0.27.3/TEST_TMP/run/cpp/numpy_subarray/numpy_subarray.so\", line 149, in numpy_subarray\r\nFailed example:\r\n    test_record_subarray()\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/usr/lib64/python2.7/doctest.py\", line 1315, in __run\r\n        compileflags, 1) in test.globs\r\n      File \"<doctest numpy_subarray[0]>\", line 1, in <module>\r\n        test_record_subarray()\r\n      File \"tests/run/numpy_subarray.pyx\", line 23, in numpy_subarray.test_record_subarray\r\n        assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),\r\n    AssertionError\r\n----------------------------------------------------------------------\r\n```\r\n\r\nHappens only on ppc64 and s390x which are BE.",
    "closed_at": "2019-01-19T14:36:12Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Thanks for the report. Could you retry it with the latest master? I added output to the assertions so that we can actually see what is wrong here. Interesting enough, that test has been around since 2013. Since I don't have such a system available, any debugging information that you could provide would be appreciated.",
            "created_at": "2017-11-06T20:30:12Z",
            "html_url": "https://github.com/cython/cython/issues/1982#issuecomment-342276620",
            "id": 342276620,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1982",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM0MjI3NjYyMA==",
            "updated_at": "2017-11-10T08:20:25Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/342276620",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "Hi,\r\nthis test is still failing with cython 0.28.2 on big endian architectures (mips, hppa, powerpc, ppc64, sparc64), see https://buildd.debian.org/status/package.php?p=cython&suite=experimental&ver=0.28.2-2 for the build logs.\r\n\r\n    ======================================================================\r\n    FAIL: numpy_subarray ()\r\n    Doctest: numpy_subarray\r\n    ----------------------------------------------------------------------\r\n    Traceback (most recent call last):\r\n      File \"/usr/lib/python2.7/doctest.py\", line 2226, in runTest\r\n        raise self.failureException(self.format_failure(new.getvalue()))\r\n    AssertionError: Failed doctest test for numpy_subarray\r\n      File \"/<<PKGBUILDDIR>>/build/work-dir/0/run/c/numpy_subarray/numpy_subarray.so\", line 488, in numpy_subarray\r\n\r\n    ----------------------------------------------------------------------\r\n    File \"/<<PKGBUILDDIR>>/build/work-dir/0/run/c/numpy_subarray/numpy_subarray.so\", line 491, in numpy_subarray\r\n    Failed example:\r\n        test_record_subarray()\r\n    Exception raised:\r\n        Traceback (most recent call last):\r\n          File \"/usr/lib/python2.7/doctest.py\", line 1315, in __run\r\n            compileflags, 1) in test.globs\r\n          File \"<doctest numpy_subarray[0]>\", line 1, in <module>\r\n            test_record_subarray()\r\n          File \"tests/run/numpy_subarray.pyx\", line 23, in numpy_subarray.test_record_subarray\r\n            assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),\r\n        AssertionError: {'a': (dtype('int32'), 0), 'b': (dtype(('>f8', (3, 3))), 4)}\r\n\r\n\r\n    ======================================================================\r\n    FAIL: numpy_subarray ()\r\n    Doctest: numpy_subarray\r\n    ----------------------------------------------------------------------\r\n    Traceback (most recent call last):\r\n      File \"/usr/lib/python2.7/doctest.py\", line 2226, in runTest\r\n        raise self.failureException(self.format_failure(new.getvalue()))\r\n    AssertionError: Failed doctest test for numpy_subarray\r\n      File \"/<<PKGBUILDDIR>>/build/work-dir/0/run/cpp/numpy_subarray/numpy_subarray.so\", line 401, in numpy_subarray\r\n\r\n    ----------------------------------------------------------------------\r\n    File \"/<<PKGBUILDDIR>>/build/work-dir/0/run/cpp/numpy_subarray/numpy_subarray.so\", line 404, in numpy_subarray\r\n    Failed example:\r\n        test_record_subarray()\r\n    Exception raised:\r\n        Traceback (most recent call last):\r\n          File \"/usr/lib/python2.7/doctest.py\", line 1315, in __run\r\n            compileflags, 1) in test.globs\r\n          File \"<doctest numpy_subarray[0]>\", line 1, in <module>\r\n            test_record_subarray()\r\n          File \"tests/run/numpy_subarray.pyx\", line 23, in numpy_subarray.test_record_subarray\r\n            assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),\r\n        AssertionError: {'a': (dtype('int32'), 0), 'b': (dtype(('>f8', (3, 3))), 4)}",
            "created_at": "2018-06-07T11:36:52Z",
            "html_url": "https://github.com/cython/cython/issues/1982#issuecomment-395389402",
            "id": 395389402,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1982",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5NTM4OTQwMg==",
            "updated_at": "2018-06-07T11:36:52Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/395389402",
            "user": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/1833581?v=4",
                "events_url": "https://api.github.com/users/tobihan/events{/privacy}",
                "followers_url": "https://api.github.com/users/tobihan/followers",
                "following_url": "https://api.github.com/users/tobihan/following{/other_user}",
                "gists_url": "https://api.github.com/users/tobihan/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tobihan",
                "id": 1833581,
                "login": "tobihan",
                "node_id": "MDQ6VXNlcjE4MzM1ODE=",
                "organizations_url": "https://api.github.com/users/tobihan/orgs",
                "received_events_url": "https://api.github.com/users/tobihan/received_events",
                "repos_url": "https://api.github.com/users/tobihan/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tobihan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tobihan/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tobihan"
            }
        },
        {
            "author_association": "NONE",
            "body": "On 0.29.3:\r\n\r\n```\r\n======================================================================\r\nFAIL: numpy_subarray ()\r\nDoctest: numpy_subarray\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/lib64/python2.7/doctest.py\", line 2226, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for numpy_subarray\r\n  File \"/builddir/build/BUILD/cython-0.29.3/TEST_TMP/run/c/numpy_subarray/numpy_subarray.so\", line 231, in numpy_subarray\r\n----------------------------------------------------------------------\r\nFile \"/builddir/build/BUILD/cython-0.29.3/TEST_TMP/run/c/numpy_subarray/numpy_subarray.so\", line 234, in numpy_subarray\r\nFailed example:\r\n    test_record_subarray()\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/usr/lib64/python2.7/doctest.py\", line 1315, in __run\r\n        compileflags, 1) in test.globs\r\n      File \"<doctest numpy_subarray[0]>\", line 1, in <module>\r\n        test_record_subarray()\r\n      File \"tests/run/numpy_subarray.pyx\", line 23, in numpy_subarray.test_record_subarray\r\n        assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),\r\n    AssertionError: {'a': (dtype('int32'), 0), 'b': (dtype(('>f8', (3, 3))), 4)}\r\n======================================================================\r\nFAIL: numpy_subarray ()\r\nDoctest: numpy_subarray\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/usr/lib64/python2.7/doctest.py\", line 2226, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for numpy_subarray\r\n  File \"/builddir/build/BUILD/cython-0.29.3/TEST_TMP/run/cpp/numpy_subarray/numpy_subarray.so\", line 228, in numpy_subarray\r\n----------------------------------------------------------------------\r\nFile \"/builddir/build/BUILD/cython-0.29.3/TEST_TMP/run/cpp/numpy_subarray/numpy_subarray.so\", line 231, in numpy_subarray\r\nFailed example:\r\n    test_record_subarray()\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/usr/lib64/python2.7/doctest.py\", line 1315, in __run\r\n        compileflags, 1) in test.globs\r\n      File \"<doctest numpy_subarray[0]>\", line 1, in <module>\r\n        test_record_subarray()\r\n      File \"tests/run/numpy_subarray.pyx\", line 23, in numpy_subarray.test_record_subarray\r\n        assert descr.fields == {'a': (py_numpy.dtype('int32'), 0),\r\n    AssertionError: {'a': (dtype('int32'), 0), 'b': (dtype(('>f8', (3, 3))), 4)}\r\n----------------------------------------------------------------------\r\nRan 11343 tests in 3764.831s\r\nFAILED (failures=2, skipped=68)\r\n```",
            "created_at": "2019-01-19T11:54:43Z",
            "html_url": "https://github.com/cython/cython/issues/1982#issuecomment-455773757",
            "id": 455773757,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1982",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ1NTc3Mzc1Nw==",
            "updated_at": "2019-01-19T11:54:43Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/455773757",
            "user": {
                "avatar_url": "https://avatars2.githubusercontent.com/u/2401856?v=4",
                "events_url": "https://api.github.com/users/hroncok/events{/privacy}",
                "followers_url": "https://api.github.com/users/hroncok/followers",
                "following_url": "https://api.github.com/users/hroncok/following{/other_user}",
                "gists_url": "https://api.github.com/users/hroncok/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/hroncok",
                "id": 2401856,
                "login": "hroncok",
                "node_id": "MDQ6VXNlcjI0MDE4NTY=",
                "organizations_url": "https://api.github.com/users/hroncok/orgs",
                "received_events_url": "https://api.github.com/users/hroncok/received_events",
                "repos_url": "https://api.github.com/users/hroncok/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/hroncok/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/hroncok/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/hroncok"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Thanks for the reports, and sorry for not resolving the issue earlier. It's really just the test that was broken here.",
            "created_at": "2019-01-19T14:37:14Z",
            "html_url": "https://github.com/cython/cython/issues/1982#issuecomment-455785741",
            "id": 455785741,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1982",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ1NTc4NTc0MQ==",
            "updated_at": "2019-01-19T14:37:45Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/455785741",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "Form the fix, I understand what was wrong. From the errors it was not so clear (I thought it expects just key a but got a and b). Thank you.",
            "created_at": "2019-01-19T14:39:30Z",
            "html_url": "https://github.com/cython/cython/issues/1982#issuecomment-455785907",
            "id": 455785907,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1982",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ1NTc4NTkwNw==",
            "updated_at": "2019-01-19T14:39:42Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/455785907",
            "user": {
                "avatar_url": "https://avatars2.githubusercontent.com/u/2401856?v=4",
                "events_url": "https://api.github.com/users/hroncok/events{/privacy}",
                "followers_url": "https://api.github.com/users/hroncok/followers",
                "following_url": "https://api.github.com/users/hroncok/following{/other_user}",
                "gists_url": "https://api.github.com/users/hroncok/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/hroncok",
                "id": 2401856,
                "login": "hroncok",
                "node_id": "MDQ6VXNlcjI0MDE4NTY=",
                "organizations_url": "https://api.github.com/users/hroncok/orgs",
                "received_events_url": "https://api.github.com/users/hroncok/received_events",
                "repos_url": "https://api.github.com/users/hroncok/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/hroncok/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/hroncok/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/hroncok"
            }
        }
    ],
    "comments": 5,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1982/comments",
    "created_at": "2017-11-06T06:09:18Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": "0a962c22acdb422e0a4956642aed5a08dcdcc1d1",
            "commit_url": "https://api.github.com/repos/cython/cython/commits/0a962c22acdb422e0a4956642aed5a08dcdcc1d1",
            "created_at": "2019-01-19T14:35:31Z",
            "event": "referenced",
            "id": 2084544429,
            "node_id": "MDE1OlJlZmVyZW5jZWRFdmVudDIwODQ1NDQ0Mjk=",
            "url": "https://api.github.com/repos/cython/cython/issues/events/2084544429"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": "0a962c22acdb422e0a4956642aed5a08dcdcc1d1",
            "commit_url": "https://api.github.com/repos/cython/cython/commits/0a962c22acdb422e0a4956642aed5a08dcdcc1d1",
            "created_at": "2019-01-19T14:36:13Z",
            "event": "closed",
            "id": 2084544675,
            "node_id": "MDExOkNsb3NlZEV2ZW50MjA4NDU0NDY3NQ==",
            "url": "https://api.github.com/repos/cython/cython/issues/events/2084544675"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2019-01-19T14:36:26Z",
            "event": "milestoned",
            "id": 2084544767,
            "milestone": {
                "title": "0.29.4"
            },
            "node_id": "MDE1Ok1pbGVzdG9uZWRFdmVudDIwODQ1NDQ3Njc=",
            "url": "https://api.github.com/repos/cython/cython/issues/events/2084544767"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2019-01-19T14:36:39Z",
            "event": "labeled",
            "id": 2084544836,
            "label": {
                "color": "444444",
                "name": "defect"
            },
            "node_id": "MDEyOkxhYmVsZWRFdmVudDIwODQ1NDQ4MzY=",
            "url": "https://api.github.com/repos/cython/cython/issues/events/2084544836"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1982/events",
    "html_url": "https://github.com/cython/cython/issues/1982",
    "id": 271368650,
    "labels": [
        {
            "color": "444444",
            "default": false,
            "id": 425553654,
            "name": "defect",
            "node_id": "MDU6TGFiZWw0MjU1NTM2NTQ=",
            "url": "https://api.github.com/repos/cython/cython/labels/defect"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1982/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": null,
        "closed_issues": 1,
        "created_at": "2019-01-19T14:36:26Z",
        "creator": {
            "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
            "events_url": "https://api.github.com/users/scoder/events{/privacy}",
            "followers_url": "https://api.github.com/users/scoder/followers",
            "following_url": "https://api.github.com/users/scoder/following{/other_user}",
            "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/scoder",
            "id": 491659,
            "login": "scoder",
            "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
            "organizations_url": "https://api.github.com/users/scoder/orgs",
            "received_events_url": "https://api.github.com/users/scoder/received_events",
            "repos_url": "https://api.github.com/users/scoder/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/scoder"
        },
        "description": null,
        "due_on": null,
        "html_url": "https://github.com/cython/cython/milestone/62",
        "id": 3986137,
        "labels_url": "https://api.github.com/repos/cython/cython/milestones/62/labels",
        "node_id": "MDk6TWlsZXN0b25lMzk4NjEzNw==",
        "number": 62,
        "open_issues": 0,
        "state": "open",
        "title": "0.29.4",
        "updated_at": "2019-01-19T14:36:26Z",
        "url": "https://api.github.com/repos/cython/cython/milestones/62"
    },
    "node_id": "MDU6SXNzdWUyNzEzNjg2NTA=",
    "number": 1982,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "title": "2 tests fail on Big Endian on 0.27.3",
    "updated_at": "2019-01-19T14:39:42Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1982",
    "user": {
        "avatar_url": "https://avatars1.githubusercontent.com/u/2866862?v=4",
        "events_url": "https://api.github.com/users/ignatenkobrain/events{/privacy}",
        "followers_url": "https://api.github.com/users/ignatenkobrain/followers",
        "following_url": "https://api.github.com/users/ignatenkobrain/following{/other_user}",
        "gists_url": "https://api.github.com/users/ignatenkobrain/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/ignatenkobrain",
        "id": 2866862,
        "login": "ignatenkobrain",
        "node_id": "MDQ6VXNlcjI4NjY4NjI=",
        "organizations_url": "https://api.github.com/users/ignatenkobrain/orgs",
        "received_events_url": "https://api.github.com/users/ignatenkobrain/received_events",
        "repos_url": "https://api.github.com/users/ignatenkobrain/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/ignatenkobrain/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ignatenkobrain/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/ignatenkobrain"
    }
}