{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Build and test log:\r\nhttps://nix-cache.s3.amazonaws.com/log/y3ml3jck19injwk6m3i2g28wjs5plkdv-python3.6-Cython-0.28.3.drv\r\n\r\nBuild information:\r\nhttps://hydra.nixos.org/build/75722086\r\n\r\n```\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\n\r\ndef __invoke():\r\n    del f''\r\n       ^\r\n------------------------------------------------------------\r\n\r\n/build/.cython/inline/_cython_inline_beb4bbef1343875f738b6e0127fe9a71.pyx:5:8: Cannot assign to or delete this\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\n\r\ndef __invoke():\r\n    del '' f''\r\n       ^\r\n------------------------------------------------------------\r\n\r\n/build/.cython/inline/_cython_inline_f66f65e88fbde95f5e537752d0e758e3.pyx:5:8: Cannot assign to or delete this\r\nwarning: /build/.cython/inline/_cython_inline_110bb1f5cf1c6d3fb43b12861e28eee1.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_2ac7e6d6135b0017092e3efaa0600c37.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_fef576f0414b8f0066acfb95092b1cbc.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_8462394424805248103b68f3371f1adb.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_38bd97cf321167b7480fcdefa9cdaa3d.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_8b8c347ab142fd959ba0ed0749fee3e0.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_659bc900a2ef89b4a630f165063dc8d1.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_7eb5b4430795aa4e7d2ff64237002c6e.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_bcfcd314c3e2b90452a153cbfa6a5cdf.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_67426d6ad1ce69a583797c9ecdb6a9ef.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_16bb4a61d5b5583bd60b5a4c19e91149.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_3cced159f9c00cecf34a8e10b0dc1aec.pyx:6:4: Unreachable code\r\nwarning: /build/.cython/inline/_cython_inline_e18ca7d3560aaf715bd6f7982617025f.pyx:6:4: Unreachable code\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\n\r\ndef __invoke():\r\n    del f''\r\n       ^\r\n------------------------------------------------------------\r\n\r\n/build/.cython/inline/_cython_inline_beb4bbef1343875f738b6e0127fe9a71.pyx:5:8: Cannot assign to or delete this\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\n\r\ndef __invoke():\r\n    del '' f''\r\n       ^\r\n------------------------------------------------------------\r\n\r\n/build/.cython/inline/_cython_inline_f66f65e88fbde95f5e537752d0e758e3.pyx:5:8: Cannot assign to or delete this\r\nunused.c:1275:18: warning: ‘__pyx_f_6unused_c_unused_optional’ defined but not used [-Wunused-function]\r\n static PyObject *__pyx_f_6unused_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct __pyx_opt_args_6unused_c_unused_optional *__pyx_optional_args) {\r\n                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\nunused.c:1228:18: warning: ‘__pyx_f_6unused_c_unused_simple’ defined but not used [-Wunused-function]\r\n static PyObject *__pyx_f_6unused_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {\r\n                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\nunused.cpp:1289:18: warning: ‘PyObject* __pyx_f_6unused_c_unused_optional(PyObject*, PyObject*, __pyx_opt_args_6unused_c_unused_optional*)’ defined but not used [-Wunused-function]\r\n static PyObject *__pyx_f_6unused_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct __pyx_opt_args_6unused_c_unused_optional *__pyx_optional_args) {\r\n                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\nunused.cpp:1242:18: warning: ‘PyObject* __pyx_f_6unused_c_unused_simple(PyObject*, PyObject*, PyObject*)’ defined but not used [-Wunused-function]\r\n static PyObject *__pyx_f_6unused_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {\r\n                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\nunused_args.c:1290:18: warning: ‘__pyx_f_11unused_args_c_unused_optional’ defined but not used [-Wunused-function]\r\n static PyObject *__pyx_f_11unused_args_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct __pyx_opt_args_11unused_args_c_unused_optional *__pyx_optional_args) {\r\n                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\nunused_args.c:1243:18: warning: ‘__pyx_f_11unused_args_c_unused_simple’ defined but not used [-Wunused-function]\r\n static PyObject *__pyx_f_11unused_args_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {\r\n                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\nunused_args.cpp:1304:18: warning: ‘PyObject* __pyx_f_11unused_args_c_unused_optional(PyObject*, PyObject*, __pyx_opt_args_11unused_args_c_unused_optional*)’ defined but not used [-Wunused-function]\r\n static PyObject *__pyx_f_11unused_args_c_unused_optional(CYTHON_UNUSED PyObject *__pyx_v_a, PyObject *__pyx_v_b, struct __pyx_opt_args_11unused_args_c_unused_optional *__pyx_optional_args) {\r\n                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\nunused_args.cpp:1257:18: warning: ‘PyObject* __pyx_f_11unused_args_c_unused_simple(PyObject*, PyObject*, PyObject*)’ defined but not used [-Wunused-function]\r\n static PyObject *__pyx_f_11unused_args_c_unused_simple(PyObject *__pyx_v_a, PyObject *__pyx_v_b, CYTHON_UNUSED PyObject *__pyx_v_c) {\r\n                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\nException ignored in: <yield_from_pep380.test_broken_getattr_handling.<locals>.Broken object at 0x7fff73704eb8>\r\nTraceback (most recent call last):\r\n  File \"tests/run/yield_from_pep380.pyx\", line 574, in yield_from_pep380.test_broken_getattr_handling.Broken.__getattr__\r\n    1/0\r\nZeroDivisionError: integer division or modulo by zero\r\nException ignored in: <yield_from_pep380.test_broken_getattr_handling.<locals>.Broken object at 0x7fff73704da0>\r\nTraceback (most recent call last):\r\n  File \"tests/run/yield_from_pep380.pyx\", line 574, in yield_from_pep380.test_broken_getattr_handling.Broken.__getattr__\r\n    1/0\r\nZeroDivisionError: integer division or modulo by zero\r\nException ignored in: <yield_from_pep380.test_broken_getattr_handling.<locals>.Broken object at 0x7ffee74bde48>\r\nTraceback (most recent call last):\r\n  File \"tests/run/yield_from_pep380.pyx\", line 574, in yield_from_pep380.test_broken_getattr_handling.Broken.__getattr__\r\n    1/0\r\nZeroDivisionError: integer division or modulo by zero\r\nException ignored in: <yield_from_pep380.test_broken_getattr_handling.<locals>.Broken object at 0x7ffee74bd828>\r\nTraceback (most recent call last):\r\n  File \"tests/run/yield_from_pep380.pyx\", line 574, in yield_from_pep380.test_broken_getattr_handling.Broken.__getattr__\r\n    1/0\r\nZeroDivisionError: integer division or modulo by zero\r\nruntests.py:1586: DeprecationWarning: Please use assertTrue instead.\r\n  \"make PYTHON='%s' CYTHON='%s' LIBDIR1='%s' test > make.output\" % (sys.executable, cython, libdir)) == 0)\r\n======================================================================\r\nERROR: runTest (__main__.CythonRunTestCase)\r\ncompiling (c) and running fstring\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"runtests.py\", line 1114, in run\r\n    ext_so_path = self.runCompileTest()\r\n  File \"runtests.py\", line 803, in runCompileTest\r\n    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)\r\n  File \"runtests.py\", line 1038, in compile\r\n    self._match_output(expected_errors, errors, tostderr)\r\n  File \"runtests.py\", line 1084, in _match_output\r\n    self.assertEqual(None, unexpected)\r\nAssertionError: None != \"509:0: Expected path '//AddNode' not found in result tree\"\r\n\r\n======================================================================\r\nERROR: runTest (__main__.CythonRunTestCase)\r\ncompiling (cpp) and running fstring\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"runtests.py\", line 1114, in run\r\n    ext_so_path = self.runCompileTest()\r\n  File \"runtests.py\", line 803, in runCompileTest\r\n    self.test_directory, self.expect_errors, self.expect_warnings, self.annotate)\r\n  File \"runtests.py\", line 1038, in compile\r\n    self._match_output(expected_errors, errors, tostderr)\r\n  File \"runtests.py\", line 1084, in _match_output\r\n    self.assertEqual(None, unexpected)\r\nAssertionError: None != \"509:0: Expected path '//AddNode' not found in result tree\"\r\n\r\n----------------------------------------------------------------------\r\nRan 11246 tests in 9091.778s\r\n```",
    "closed_at": "2018-06-10T18:24:53Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Thanks for the report.\r\n\r\nThe long first part is only stray output of (correct) tests for error cases. We could try harder to suppress that output, but they are nothing to worry about.\r\n\r\nThere are also a couple of \"unused code\" warnings by the C compiler. They are annoying and thus worth fixing, but apart from that, they do not have a real impact on Cython users.\r\n\r\nI just fixed the `DeprecationWarning` in master (1f1aeb8af72ed32307e7ff8ac2390ed930962698). That's in the test runner, so nothing critical.\r\n\r\nThe last two actual errors are unfortunate. I fixed those right before the release (c485b1b77264c3c75d090a3c526de24966830d42), but it seems that they slipped into the source release somehow. Resolving this would require a new release - but since it's really only the test that is broken here and nothing in the code, and thus the binary distributions and whatever people build from the sdist are all perfectly ok, it seems wasteful to issue a completely new release just for that...\r\n\r\nSorry for that slip. I think the best for now is to disable the tests for this exact release, so that you can build binaries. If these are the only errors you got for the release, it's completely safe to use.",
            "created_at": "2018-06-10T09:24:39Z",
            "html_url": "https://github.com/cython/cython/issues/2319#issuecomment-396034301",
            "id": 396034301,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/2319",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5NjAzNDMwMQ==",
            "updated_at": "2018-06-10T09:30:14Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/396034301",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "> The last two actual errors are unfortunate. I fixed those right before the release (c485b1b), but it seems that they slipped into the source release somehow. Resolving this would require a new release - but since it's really only the test that is broken here and nothing in the code, and thus the binary distributions and whatever people build from the sdist are all perfectly ok, it seems wasteful to issue a completely new release just for that...\r\n\r\nDoes that mean the PyPI `sdist` corresponds to a build from just before the tagged version? For now I've added the change as a patch in our builds so the tests succeed.\r\n\r\nThanks for the quick an elaborate reply!",
            "created_at": "2018-06-10T18:24:53Z",
            "html_url": "https://github.com/cython/cython/issues/2319#issuecomment-396070375",
            "id": 396070375,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/2319",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5NjA3MDM3NQ==",
            "updated_at": "2018-06-10T18:24:53Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/396070375",
            "user": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/2129135?v=4",
                "events_url": "https://api.github.com/users/FRidh/events{/privacy}",
                "followers_url": "https://api.github.com/users/FRidh/followers",
                "following_url": "https://api.github.com/users/FRidh/following{/other_user}",
                "gists_url": "https://api.github.com/users/FRidh/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/FRidh",
                "id": 2129135,
                "login": "FRidh",
                "node_id": "MDQ6VXNlcjIxMjkxMzU=",
                "organizations_url": "https://api.github.com/users/FRidh/orgs",
                "received_events_url": "https://api.github.com/users/FRidh/received_events",
                "repos_url": "https://api.github.com/users/FRidh/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/FRidh/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/FRidh/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/FRidh"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Does that mean the PyPI sdist corresponds to a build from just before the tagged version?\r\n\r\nYes.",
            "created_at": "2018-06-10T18:27:26Z",
            "html_url": "https://github.com/cython/cython/issues/2319#issuecomment-396070538",
            "id": 396070538,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/2319",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM5NjA3MDUzOA==",
            "updated_at": "2018-06-10T18:27:26Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/396070538",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/2319/comments",
    "created_at": "2018-06-10T09:00:49Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": "1f1aeb8af72ed32307e7ff8ac2390ed930962698",
            "commit_url": "https://api.github.com/repos/cython/cython/commits/1f1aeb8af72ed32307e7ff8ac2390ed930962698",
            "created_at": "2018-06-10T09:25:00Z",
            "event": "referenced",
            "id": 1672557384,
            "node_id": "MDE1OlJlZmVyZW5jZWRFdmVudDE2NzI1NTczODQ=",
            "url": "https://api.github.com/repos/cython/cython/issues/events/1672557384"
        },
        {
            "actor": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/2129135?v=4",
                "events_url": "https://api.github.com/users/FRidh/events{/privacy}",
                "followers_url": "https://api.github.com/users/FRidh/followers",
                "following_url": "https://api.github.com/users/FRidh/following{/other_user}",
                "gists_url": "https://api.github.com/users/FRidh/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/FRidh",
                "id": 2129135,
                "login": "FRidh",
                "node_id": "MDQ6VXNlcjIxMjkxMzU=",
                "organizations_url": "https://api.github.com/users/FRidh/orgs",
                "received_events_url": "https://api.github.com/users/FRidh/received_events",
                "repos_url": "https://api.github.com/users/FRidh/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/FRidh/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/FRidh/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/FRidh"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2018-06-10T18:24:53Z",
            "event": "closed",
            "id": 1672725493,
            "node_id": "MDExOkNsb3NlZEV2ZW50MTY3MjcyNTQ5Mw==",
            "url": "https://api.github.com/repos/cython/cython/issues/events/1672725493"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/2319/events",
    "html_url": "https://github.com/cython/cython/issues/2319",
    "id": 330952409,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/2319/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUzMzA5NTI0MDk=",
    "number": 2319,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "title": "Failing tests with 0.28.3",
    "updated_at": "2018-06-10T18:27:27Z",
    "url": "https://api.github.com/repos/cython/cython/issues/2319",
    "user": {
        "avatar_url": "https://avatars3.githubusercontent.com/u/2129135?v=4",
        "events_url": "https://api.github.com/users/FRidh/events{/privacy}",
        "followers_url": "https://api.github.com/users/FRidh/followers",
        "following_url": "https://api.github.com/users/FRidh/following{/other_user}",
        "gists_url": "https://api.github.com/users/FRidh/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/FRidh",
        "id": 2129135,
        "login": "FRidh",
        "node_id": "MDQ6VXNlcjIxMjkxMzU=",
        "organizations_url": "https://api.github.com/users/FRidh/orgs",
        "received_events_url": "https://api.github.com/users/FRidh/received_events",
        "repos_url": "https://api.github.com/users/FRidh/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/FRidh/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/FRidh/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/FRidh"
    }
}