{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "This is a simple cython file that causes the compiler crash,`test.pyx`\r\n\r\n```cython\r\nimport numpy as np\r\ncimport numpy as np\r\nnp.import_array()\r\ndef foo():\r\n    cdef extern from \"numpy/arrayobject.h\":\r\n        void PyArray_ENABLEFLAGS(np.ndarray arr, int flags)\r\n```\r\n\r\nThis is my `setup.py`:\r\n\r\n```python\r\nfrom distutils.core import setup\r\nfrom distutils.extension import Extension\r\nfrom Cython.Distutils import build_ext\r\nimport numpy as np\r\nsetup(\r\n    cmdclass={'build_ext': build_ext},\r\n    ext_modules=[Extension(\"test\", [\"test.pyx\"], include_dirs=[np.get_include()])],\r\n)\r\n```\r\n\r\nThis is the Error I get with Cython 0.28.6 (Python 2.7.15, Numpy 1.15.1, Fedora 29):\r\n\r\n```\r\nrunning build_ext\r\ncythoning test.pyx to test.c\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\nimport numpy as np\r\ncimport numpy as np\r\nnp.import_array()\r\ndef foo():\r\n    cdef extern from \"numpy/arrayobject.h\":\r\n        ^\r\n------------------------------------------------------------\r\n\r\ntest.pyx:5:9: Compiler crash in AnalyseDeclarationsTransform\r\n\r\nModuleNode.body = StatListNode(test.pyx:1:0)\r\nStatListNode.stats[3] = StatListNode(test.pyx:4:0)\r\nStatListNode.stats[0] = DefNode(test.pyx:4:0,\r\n    modifiers = [...]/0,\r\n    name = u'foo',\r\n    np_args_idx = [...]/0,\r\n    py_wrapper_required = True,\r\n    reqd_kw_flags_cname = '0')\r\nFile 'Nodes.py', line 427, in analyse_declarations: StatListNode(test.pyx:5:9)\r\nFile 'Nodes.py', line 495, in analyse_declarations: CDefExternNode(test.pyx:5:9,\r\n    include_file = u'numpy/arrayobject.h')\r\n\r\nCompiler crash traceback from this point on:\r\n  File \"/usr/lib64/python2.7/site-packages/Cython/Compiler/Nodes.py\", line 495, in analyse_declarations\r\n    env.add_include_file(self.include_file, self.verbatim_include, late)\r\nTypeError: add_include_file() takes exactly 2 arguments (4 given)\r\n```\r\n\r\nI'm not sure if this is valid Cython code, but if it is not, a compiler crash does not seem to be the right result.",
    "closed_at": "2019-01-18T12:52:21Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Could you try 0.29.x? It's probably fixed there.",
            "created_at": "2019-01-18T12:33:11Z",
            "html_url": "https://github.com/cython/cython/issues/2804#issuecomment-455531458",
            "id": 455531458,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/2804",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ1NTUzMTQ1OA==",
            "updated_at": "2019-01-18T12:33:11Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/455531458",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "You're right. It compiles with 0.29.2",
            "created_at": "2019-01-18T12:52:21Z",
            "html_url": "https://github.com/cython/cython/issues/2804#issuecomment-455536150",
            "id": 455536150,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/2804",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQ1NTUzNjE1MA==",
            "updated_at": "2019-01-18T12:52:21Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/455536150",
            "user": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/99431?v=4",
                "events_url": "https://api.github.com/users/tovrstra/events{/privacy}",
                "followers_url": "https://api.github.com/users/tovrstra/followers",
                "following_url": "https://api.github.com/users/tovrstra/following{/other_user}",
                "gists_url": "https://api.github.com/users/tovrstra/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tovrstra",
                "id": 99431,
                "login": "tovrstra",
                "node_id": "MDQ6VXNlcjk5NDMx",
                "organizations_url": "https://api.github.com/users/tovrstra/orgs",
                "received_events_url": "https://api.github.com/users/tovrstra/received_events",
                "repos_url": "https://api.github.com/users/tovrstra/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tovrstra/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tovrstra/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tovrstra"
            }
        }
    ],
    "comments": 2,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/2804/comments",
    "created_at": "2019-01-18T11:53:07Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/99431?v=4",
                "events_url": "https://api.github.com/users/tovrstra/events{/privacy}",
                "followers_url": "https://api.github.com/users/tovrstra/followers",
                "following_url": "https://api.github.com/users/tovrstra/following{/other_user}",
                "gists_url": "https://api.github.com/users/tovrstra/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tovrstra",
                "id": 99431,
                "login": "tovrstra",
                "node_id": "MDQ6VXNlcjk5NDMx",
                "organizations_url": "https://api.github.com/users/tovrstra/orgs",
                "received_events_url": "https://api.github.com/users/tovrstra/received_events",
                "repos_url": "https://api.github.com/users/tovrstra/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tovrstra/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tovrstra/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tovrstra"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2019-01-18T12:52:21Z",
            "event": "closed",
            "id": 2082836290,
            "node_id": "MDExOkNsb3NlZEV2ZW50MjA4MjgzNjI5MA==",
            "url": "https://api.github.com/repos/cython/cython/issues/events/2082836290"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/2804/events",
    "html_url": "https://github.com/cython/cython/issues/2804",
    "id": 400693476,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/2804/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU0MDA2OTM0NzY=",
    "number": 2804,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "title": "Compiler crash with cdef extern inside def.",
    "updated_at": "2019-01-18T12:52:21Z",
    "url": "https://api.github.com/repos/cython/cython/issues/2804",
    "user": {
        "avatar_url": "https://avatars3.githubusercontent.com/u/99431?v=4",
        "events_url": "https://api.github.com/users/tovrstra/events{/privacy}",
        "followers_url": "https://api.github.com/users/tovrstra/followers",
        "following_url": "https://api.github.com/users/tovrstra/following{/other_user}",
        "gists_url": "https://api.github.com/users/tovrstra/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/tovrstra",
        "id": 99431,
        "login": "tovrstra",
        "node_id": "MDQ6VXNlcjk5NDMx",
        "organizations_url": "https://api.github.com/users/tovrstra/orgs",
        "received_events_url": "https://api.github.com/users/tovrstra/received_events",
        "repos_url": "https://api.github.com/users/tovrstra/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/tovrstra/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tovrstra/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/tovrstra"
    }
}